// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function toCurrencyValue(marker, value) {
  return marker + value.toString();
}

var CurrencyTools = {
  toCurrencyValue: toCurrencyValue
};

export {
  CurrencyTools ,
  
}
/* No side effect */
