// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Content from "../components/Content.bs.js";
import * as Sidebar from "../components/Sidebar.bs.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as MaterialUi_Grid from "@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js";
import * as Core from "@material-ui/core";
import * as Caml_js_exceptions from "bs-platform/lib/es6/caml_js_exceptions.js";
import * as MaterialUi_Container from "@jsiebern/bs-material-ui/src/MaterialUi_Container.bs.js";

function Index(Props) {
  var items = Props.items;
  var match = React.useState(function () {
        
      });
  var setSelection = match[1];
  var selection = match[0];
  var selectionHandler = function (_id) {
    var item;
    try {
      item = Caml_option.undefined_to_opt(items.find(function (x) {
                return x.id === _id;
              }));
    }
    catch (raw_exn){
      var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
      if (exn.RE_EXN_ID === "Not_found") {
        console.log("Not found");
        return ;
      }
      throw exn;
    }
    return Curry._1(setSelection, (function (param) {
                  return item;
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement(Core.Container, {
                  children: React.createElement(Core.Grid, {
                        children: null,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Content.make, {
                                  setSelection: selectionHandler,
                                  selection: selection,
                                  items: items
                                }),
                            container: true,
                            direction: "column",
                            item: true,
                            wrap: "nowrap",
                            xs: MaterialUi_Grid.Xs._8
                          }), React.createElement(Core.Grid, {
                            children: React.createElement(Sidebar.make, {
                                  selection: selection,
                                  onCloseSelection: (function (param) {
                                      return Curry._1(setSelection, (function (param) {
                                                    
                                                  }));
                                    })
                                }),
                            item: true,
                            xs: MaterialUi_Grid.Xs._4
                          })),
                  disableGutters: true,
                  maxWidth: MaterialUi_Container.MaxWidth._false
                }));
}

function getStaticProps(_ctx) {
  return {
          props: {
            items: [
              {
                id: 1,
                type_: "savings",
                accountName: "1234567****-YAHOP",
                status: "Active",
                currency: "USD",
                balance: 2.344,
                notes: ""
              },
              {
                id: 2,
                type_: "checking",
                accountName: "1234567****-WALOP",
                status: "Active",
                currency: "USD",
                balance: 6.344,
                notes: ""
              },
              {
                id: 3,
                type_: "checking",
                accountName: "1234567****-ANDER",
                status: "Deactived",
                currency: "USD",
                balance: 1.344,
                notes: ""
              }
            ]
          }
        };
}

var make = Index;

var $$default = Index;

export {
  make ,
  getStaticProps ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
